---
title: "Research"
output: html_document
---

<head>
<style>
body {
  font-family: 'Trebuchet MS', sans-serif;
}
</style>
</head>
<body>


<i> <b> Published Papers </i> </b>
 <br>
 
- <b> International Differences in Gradients in Early Childhood Overweight and Obesity: The Role of Maternal Employment and Formal Childcare Attendance</b> with Lidia Panico, et al. (2023). <i> European Journal of Public Health. </i>  [URL](https://academic.oup.com/eurpub/advance-article/doi/10.1093/eurpub/ckad058/7126956).
 
- <b> The Role of Energy Balance Related Behaviors in Socioeconomic Inequalities in Childhood Body Mass Index: A Comparative Analysis of Germany, the Netherlands, the United Kingdom, and the United States</b> with Sanneke de la Rie, et al. (2022). <i> Social Science & Medicine. </i> [URL](https://www.sciencedirect.com/science/article/pii/S0277953622008814?via%3Dihub).


 <br>
 <i> <b> Working Papers </i> </b>
 <br>

 
- <b> The Motherhood Penalty: Gender Norms, Occupational Sorting, and Labour Supply </b>  with Jonathan Norris, and Agnese Romiti. [IZA Discussion Paper](https://docs.iza.org/dp17334.pdf). <i> Under review. </i>
 <br>
Abstract: In this paper, we examine how pre-birth gender norms shape women’s labor market trajectories and occupational choices around motherhood in the United Kingdom. Using data from the British Household Panel Survey, we first quantify the impact of gender norms on earnings and labor supply post-childbirth. Our results show that traditional mothers experience a 18-percentage-point (pp) higher motherhood penalty in earnings and a 20-pp higher motherhood penalty in hours worked compared to egalitarian mothers. Second, we investigate the role of pre-birth comparative advantage within couples, finding that this mechanism applies only to egalitarian parents. Third, we examine the interaction between occupational characteristics, including their degree of family-friendliness, and pre-birth gender norms. We find that accounting for occupational sorting significantly reduces the
average earnings penalty for both traditional and egalitarian mothers, driven entirely by hours worked for traditional mothers. In addition, we show that occupational sorting explains 80% of the short-run earnings penalty gap between traditional and egalitarian and eliminates the difference in hours worked penalties entirely. Thus, traditional women seem to sort pre-birth into occupations that facilitate a larger reduction in hours worked post-motherhood, which in turn have a substantial impact on their earnings trajectory.
 </br>


- <b> Beliefs on Children's Human Capital Formation and Mothers at Work </b> with Jonathan Norris, Agnese Romiti, Zhan Shi, and Paul Telemo.  [IZA Discussion Paper](https://docs.iza.org/dp17574.pdf). <i> Under review. </i>
 <br>
Abstract: Mothers may face pressure to sort out of the labor market due to perceptions that women have an absolute advantage in child-rearing, even when their earnings potential matches that of men. Guided by a simple model, we use a survey experiment where we equalize earnings potential across gender and show that women are perceived to hold an absolute advantage in childrearing. We then experimentally test mechanisms underlying these beliefs, finding that mothers are expected to spend more time on skill investments with their children than fathers who have equivalent time available. Finally, we find that when mothers work full-time, children’s actual performance is generally underestimated, but providing factual information about their outcomes, leads to more accurate beliefs and reduced expectations of harm to the child. Our results show that beliefs about an absolute advantage for women in child-rearing are indeed present and highlight the need for targeted interventions to address misinformation about children’s outcomes when mothers pursue careers.
 </br>


 <br>
 <i> <b> Work in Progress </i> </b>
 <br>

- <b>The Transition from Universal to Means-Tested Benefits in France: Effets on Families and Children</b> with Lidia Panico and Agnese Romiti.
 
- <b>Gender Differences in Cognitive Ability at School Entry: the Role of School Readiness Skills </b> with Lidia Panico and Michelle Kelly-Irving.


 <br>
<i> <b> Presentations & Invited Seminars </i> </b>
 <br>

- <b> 2024 : </b> PGR conference, University of Strathclyde, Glasgow – UK | Scottish Graduate Programme in Economics (SGPE) Annual Conference, Crieff – UK (*Awarded Best Presentation Prize*)

- <b> 2023: </b> AIEL Conference, University of Genoa – Italy | Royal Economic Society PhD Conference, University of Glasgow, Glasgow - UK | PGR conference, University of Strathclyde, Glasgow – UK.


- <b> 2022: </b> PGR conference, University of Strathclyde, Glasgow – UK.

- <b> 2020: </b> RC28, Turku – Finland (*accepted to present but cancelled due to the pandemic*).


 <br>
<i> <b> Project Participation </i> </b>
 <br>
 
- Data Manager for the [DICE](www.dice.site.ined.fr) project: <br>
The Development of Inequalities in Child Educational Achievement: A Six Country Study (DICE) is an Open Research Area (ORA)-funded project which aimed to advance our understanding of disparities in child development by parental socioeconomic status. It leveraged rich cohort and administrative data from six countries - France, Germany, Japan, the Netherlands, the United Kingdom, and the United States – embedding them in a harmonized framework. The project moved beyond cross-sectional and single country snapshots by studying the question of how inequalities develop over time (ages 3 to 16), what factors may influence inequalities and how national context may strengthen or buffer these processes. Child development is conceptualised broadly, to include cognitive, social/emotional and health outcomes, recognizing the interplay of multiple spheres of development in childhood.
<br>



